# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb16acd3346e024e8b6f42ae7c19c4d4583edaf6b3b1d412cff2587b05bf466757cb964a8b22dfd87f3e30b6860012b4f04d9f7b4b5763b50b7f36593fcb0a0
  STEAM_WEB_API_KEY: D00A20377C8B49B75F880F887389D958
test:
  secret_key_base: 8fffb88e70c93f8d81f06c789afc94d661cfc2a1f8848071a1f20a91e64792a9f28c77410ef7ee5f6f219dbd25a9495e1d9cff2eb62441e0a0172f6e41892773
  STEAM_WEB_API_KEY: D00A20377C8B49B75F880F887389D958
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  STEAM_WEB_API_KEY: D00A20377C8B49B75F880F887389D958
  # STEAM_WEB_API_KEY: <%=  %>
